name: latsol
description: Final Project

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  google_sign_in: ^5.3.3
  dio: ^4.0.6
  cloud_firestore: ^3.1.18
  firebase_messaging: ^11.4.2
  flutter_html: ^2.2.1
  firebase_storage: ^10.2.18
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/auth/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_playstore.png"
